update setenv.sh template
* Uncomment a couple of sections in the setenv.sh template that have
been mistakingly commented:
  - check for spaces in the BAMBOO_HOME

* Uncomment bit to set PermGen if `permgen.sh` is present.  PermGen is
deprecated in Bamboo >= 5.10/Java 1.8, but this module supports older
versions.

diff --git a/templates/setenv.sh.erb b/templates/setenv.sh.erb
--- a/templates/setenv.sh.erb
+++ b/templates/setenv.sh.erb
@@ -37,21 +37,18 @@ CATALINA_PID="<%= @appdir %>/work/catalina.pid"
 PRGDIR=`dirname "$0"`
 cat "${PRGDIR}"/bamboobanner.txt
 
-#BAMBOO_HOME_MINUSD=""
-#if [ "$BAMBOO_HOME" != "" ]; then
-#    echo $BAMBOO_HOME | grep -q " "
-#    if [ $? -eq 0 ]; then
-#	    echo ""
-#	    echo "----------------------------------------------------------------------------------------------------------------------"
-#		echo "   WARNING : You cannot have a BAMBOO_HOME environment variable set with spaces in it.  This variable is being ignored"
-#	    echo "----------------------------------------------------------------------------------------------------------------------"
-#   else
-#		BAMBOO_HOME_MINUSD=-Dbamboo.home=$BAMBOO_HOME
-#   fi
-#i
-
-JAVA_OPTS="<%= @jvm_opts %> -Xms${JVM_MINIMUM_MEMORY} -Xmx${JVM_MAXIMUM_MEMORY} ${JAVA_OPTS} ${JVM_REQUIRED_ARGS} ${JVM_SUPPORT_RECOMMENDED_ARGS} " #${BAMBOO_HOME_MINUSD}"
-
+BAMBOO_HOME_MINUSD=""
+if [ "$BAMBOO_HOME" != "" ]; then
+    echo $BAMBOO_HOME | grep -q " "
+    if [ $? -eq 0 ]; then
+	    echo ""
+	    echo "----------------------------------------------------------------------------------------------------------------------"
+		echo "   WARNING : You cannot have a BAMBOO_HOME environment variable set with spaces in it.  This variable is being ignored"
+	    echo "----------------------------------------------------------------------------------------------------------------------"
+   else
+		BAMBOO_HOME_MINUSD=-Dbamboo.home=$BAMBOO_HOME
+   fi
+fi
 
 # Perm Gen size needs to be increased if encountering OutOfMemoryError: PermGen problems. Specifying PermGen size is not valid on IBM JDKs
 BAMBOO_MAX_PERM_SIZE=<%= @jvm_permgen %>
@@ -66,12 +63,13 @@ if [ -f "${PRGDIR}/permgen.sh" ]; then
     fi
 fi
 
+JAVA_OPTS="<%= @jvm_opts %> -Xms${JVM_MINIMUM_MEMORY} -Xmx${JVM_MAXIMUM_MEMORY} ${JAVA_OPTS} ${JVM_REQUIRED_ARGS} ${JVM_SUPPORT_RECOMMENDED_ARGS} ${BAMBOO_HOME_MINUSD}"
 JAVA_OPTS=$(echo "$JAVA_OPTS" | sed -e 's/\s*$//' -e 's/^\s*//')
 export JAVA_OPTS
 
 echo ""
 echo "If you encounter issues starting or stopping Bamboo Server, please see the Troubleshooting guide at https://confluence.atlassian.com/display/BAMBOO/Installing+and+upgrading+Bamboo"
 echo ""
-#if [ "$BAMBOO_HOME_MINUSD" != "" ]; then
-#    echo "Using BAMBOO_HOME:       $BAMBOO_HOME"
-#fi
+if [ "$BAMBOO_HOME_MINUSD" != "" ]; then
+    echo "Using BAMBOO_HOME:       $BAMBOO_HOME"
+fi
